MinBZK/ai-validation

docs/Way-of-Working/Onboarding/Dev-machine.md
I took our Mattermost conversation and copied it here
=> Added Dev-machine.md

docs/Way-of-Working/Onboarding/Accounts.md
=> Add onboarding doc on accounts

.github/dependabot.yml
forgot to add the version field in the dependabot.yaml.
=> fix version field in dependabot.yml

docs/ADRs/0001-adrs.md
Made headers optional for ADR template
=> add optional headers to ADR

docs/ADRs/0004-software-hosting-platform.md
Added ADR 0004 for software hosting platform
=> add ADR 0004: software hosting platform

mkdocs.yml
Add code copy to mkdocs, so that code blocks get a "copy" button.
=> Add code copy to mkdocs

docs/ADRs/0005-python-tooling.md
added python standards and tooling ADR
=> Add python tooling and standards ADR

docs/ADRs/0006-agile-tooling.md
Added an ADR for agile process tolling
=> Add agile process tooling ADR

docs/ADRs/0007-commit-convention.md
Added an ADR for commit message convention
=> Add commit message convention ADR

docs/Way-of-Working/Onboarding/Dev-machine.md
While setting up my new Mac, I used this guide. Via this PR, I would like to make some suggestions and extend the installation guide.
=> Extend doc for setting up your Dev Machine

docs/Way-of-Working/Onboarding/Accounts.md, docs/Way-of-Working/Onboarding/index.md
- Streamline onboarding a little more
- Refer to our principles when it comes to anonymity
- Refer to our principles and ADRS
=> Streamline onboarding a little more

.devcontainer/devcontainer.json, .github/dependabot.yml, .vscode/launch.json
For easy development added a devcontainer
=> Add devcontainer

docs/Way-of-Working/Onboarding/Dev-machine.md
Adds a guide for setting up  TabbyML as local coding assistant.
=> Add coding assistant

docs/Way-of-Working/Onboarding/Dev-machine.md
Indentation was broken and didn't render correctly.
=> Fix indentation

docs/ADRs/0010-container-registry.md
Add ADR 10 for a Container Registry
=> Add ADR 10 for a Container Registry

docs/ADRs/0006-agile-tooling.md, docs/ADRs/0008-architectural-diagram-tooling.md
=> Fix format ADRs

docs/Way-of-Working/Code-Reviews.md
As discussed in the Retro i added a WoW document for code reviews
=> Add WoW for code reviews

docs/Way-of-Working/UbiquitousLanguage.md
One of the action points from the recent retro was the wish for a list of terms used within our team. This document is the first setup for that wish.
=> Add Ubiquitous Language reference

SECURITY.md
Added security reporting standard
=> Add security md file

.github/workflows/stale.yml
Added a Stale PR and Issue checker.
=> Add stale checker for PR and Issues

SECURITY.md
Made a typo in the version of CVSS. fixed it in this PR
=> Fix typo in security.md

docs/Projects/TAD/index.md
line 38 and line 41 are the same, so I am removing line 38 :)
=> remove double entry in comparison list

docs/Projects/TAD/index.md
Removed a Law from California from our checklist, as it is not deemed important for us
=> Removed the California Privacy as it is not applicable

docs/Way-of-Working/Principles.md, docs/index.md, mkdocs.yml
Small changes to the landing page
=> Update our landing page

docs/Projects/TAD/index.md
There is an duplicate entry :)
=> Remove duplicate entry in functionality part of the tool checklist

docs/Projects/TAD/Reporting-Standard/0.1a1.md
=> Typo artifacts in schema 0.1a1.md

docs/Projects/TAD/Reporting-Standard/0.1a1.md
=> Fix spelling of HuggingFace

.github/pull_request_template.md
This PR adds a DCO agreement to PRs. DCO is created by the LInux foundation. The Developer Certificate of Origin (DCO) is a legal statement asserting that the contributor created the code or has the right to submit it.
=> Add DCO agreement

docs/ADRs/0012-dictionary-for-spelling.md
=> Add ADR for dictionary for spelling

docs/ADRs/0013-date-time-representation.md
Add an ADR to use ISO 8601
Version 1.1
work with modifications, whether …
=> Add an ADR to use ISO 8601

docs/Projects/TAD/ADRs/0001-adrs.md, docs/Projects/TAD/ADRs/0002-tad-reporting-standard.md
Created an ADR directory for TAD with an ADR about our TAD Reporting Standard. 
Version 1.1
license and I have the right under that …
=> Add ADR about TAD standard

requirements.txt
Reverts MinBZK/ai-validation#114
=> Revert "Bump mkdocs from 1.5.3 to 1.6.0"

docs/Way-of-Working/Decision-Log.md, docs/Way-of-Working/Onboarding/index.md
=> Add decision log

aivalidation_dictionary.txt, docs/Projects/LLM-benchmarks/index.md
Version 1.1
work with modifications, whether created in whole or in part …
=> Add project description for llm benchmark

docs/Projects/TAD/Reporting-Standard/latest.md
Version 1.1
work with modifications, whether created in whole or in part …
=> Add changelog for v0.1a3

docs/About/team.md
Add Willy to alumni section on team page.
Version 1.1
work with …
=> Add Willy to alumni section on team page

docs/Way-of-Working/Offboarding.md, docs/Way-of-Working/Onboarding/Accounts.md
Add off boarding guide
Version 1.1
work with modifications, whether …
=> Add off boarding guide

docs/Projects/TAD/ADRs/0003-tad-tool.md
This is an ADR proposal for creating our own TAD tool.
=> Add ADR for TAD tool development

aivalidation_dictionary.txt, docs/Projects/TAD/index.md
Project Description added for the TAD project with a little FAQ section
Version 1.1
license and I have the right under that license to …
=> Initial version of project description for TAD Project

docs/projects/tad/index.md
=> Minor rewrite of the project description to solve duplication

docs/index.md, mkdocs.yml
=> Adds graph to visually display our projects

docs/projects/tad/reporting-standard/0.1a3.md
Added data provenance to System, Model and Assessment Card to capture metadata in case these cards are generation from other source files.
Version 1.1
of my knowledge, is covered under an …
=> Add data provenance to system card

mkdocs.yml
Fix missing page of reporting standard 0.1a3
- [x ]  I have tested the changes locally and verified that they work as expected.
- [ x]  I have followed the project's coding conventions and style guidelines.
- [ x]  I have rebased my branch onto the latest commit of the main branch.
- [ x]  I have squashed or reorganized my commits into logical units.
- [ x]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilizes.
Version 1.1
Developer's Certificate of …
=> Fix missing page of reporting standard 0.1a3

docs/way-of-working/onboarding/accounts.md
=> Add Tuple to onboarding

docs/way-of-working/onboarding/dev-machine.md
Added brew install command to install pre-commit on your machine
- [ x]  I have tested the changes locally and verified that they work as expected.
- [x ]  I have followed the project's coding conventions and style guidelines.
- [x ]  I have rebased my branch onto the latest commit of the main branch.
- [x ]  I have squashed or reorganized my commits into logical units.
- [x ]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilizes.
Version 1.1 …
=> Add pre-commit to install of dev machine

.github/CODEOWNERS, .github/workflows/automerge.yml, aivalidation_dictionary.txt
=> Add automerge for dependabot & pre-commit and change CODEOWNERS

docs/way-of-working/onboarding/accounts.md
Add a description on how to access secret manager
Version 1.1
work with …
=> Add secret manager description

docs/projects/tad/adrs/0005-ai-verify-technical-tests.md
=> Add ADR for using AI Verify for running technical tests

docs/projects/tad/adrs/0006-extend-system-card-EU-AI-Act.md, docs/projects/tad/reporting-standard/0.1a2.md, docs/projects/tad/reporting-standard/0.1a3.md, docs/projects/tad/reporting-standard/0.1a4.md, docs/projects/tad/reporting-standard/latest.md, mkdocs.yml
Draft PR for an ADR to make a decision about how we can facilitate the technical documentation of the EU AI Act with the TAD tool. 
More details on the content of the technical documentation can be found on [Click-Up](https://app.clickup.com/9015737202/v/dc/8cp2evj-515/8cp2evj-315)
Version 1.1
have the right to submit it under the open source …
=> Add ADR for extending System Card to facilitate for EU AI Act

docs/index.md
=> Fix product graph

docs/adrs/0016-government-cloud-comparison.md
Fix broken link in ADR-0016
Version 1.1
work with modifications, whether …
=> Fix broken link in ADR-0016

docs/way-of-working/decision-log.md
Update the decision log, to include that we create a regression test when we encounter a bug in our own software.
Version 1.1
license and …
=> Add regression test on bug

docs/index.md
Add Instrument Registry to our product graph:
=> Add Instrument Registry to our product graph

aivalidation_dictionary.txt, docs/adrs/0016-government-cloud-comparison.md
Add the pros and cons of the standard platform in the overview of cloud providers within the Dutch Government
Version 1.1
license and I …
=> Extend with info on Standaard Platform

docs/projects/amt/reporting-standard/0.1a7.md, mkdocs.yml
Adds selected instruments to system card. This is needed because the system card needs to contains URNs of instruments that need to be executed to fill it. This field is also assumed to be present in this PR: https://github.com/MinBZK/tad/pull/72
Version 1.1
(b) …
=> Add selected instrument urns to systemcard

aivalidation_dictionary.txt, docs/projects/amt/adrs/0004-software-stack.md
Updated front end description with styling decisions.
Version 1.1
work …
=> Updated front end description with styling decisions

docs/way-of-working/onboarding/dev-machine.md
Add tuple installation to onboarding
=> Add tuple installation to onboarding

aivalidation_dictionary.txt, docs/projects/amt/reporting-standard/latest.md, docs/projects/amt/reporting-standard/schemas/assessmentcard_schema.json, docs/projects/amt/reporting-standard/schemas/modelcard_schema.json, docs/projects/amt/reporting-standard/schemas/systemcard_schema.json, docs/projects/amt/reporting-standard/script/validate
Add json schemas for system card, model card and assessment card
- Add json schemas
- Add validation script 
- Adjust .md files for website
Resolves #171 
=> Add json schemas for system card, model card and assessment card

docs/projects/amt/reporting-standard/0.1a8.md, mkdocs.yml
Add name field to model card. This was missing.
Version 1.1
work with …
=> Add name field to model card

docs/index.md, docs/projects/amt/adrs/0006-extend-system-card-EU-AI-Act.md, docs/projects/amt/reporting-standard/0.1a7.md, docs/projects/amt/reporting-standard/0.1a8.md, docs/projects/amt/reporting-standard/latest.md, docs/projects/amt/reporting-standard/schemas/assessmentcard_schema.json, docs/projects/amt/reporting-standard/schemas/systemcard_schema.json
Renamed all mentions of the Instrument Register to Task Registry
Version 1.1
license and I have the right under that license to submit …
=> Rename Instrument Register to Task Registry

docs/projects/amt/reporting-standard/0.1a10.md, mkdocs.yml
In this PR, we introduce the following new fields to the system cards:
- Fields for storing requirements, including URN, state, and version.
- Fields for storing measures, including URN, state, value, and version.
Version 1.1
(b) The contribution is based upon …
=> Add requirements and measures to systemcard

docs/projects/amt/reporting-standard/0.1a10.md
=> Remove latest label

docs/index.md, docs/projects/amt/adrs/0008-systemcard-storage.md, docs/projects/amt/index.md
In this PR we: 
- Add an ADR on system card storage
- Include the current ambition of AMT in the index.md 
- Add links to the decision tree and AMT on the home page
Version 1.1
of my knowledge, is …
=> Update our team website with current ambition + ADR on systemcard storage 

.github/workflows/ci.yml
=> Fix ci to include token for material insiders

overrides/partials/parallax.html, overrides/partials/parallax/ai-act_support_tool.html
Rename of the AI Act Decision tree to AI Act Support Tool, also including the change of the links
Version 1.1
license and I have the …
=> Rename ai-act-decision-tree to ai-act-support-tool

docs/projects/amt/reporting-standard/0.1a11.md, docs/projects/amt/reporting-standard/latest.md
Add the possibility to add functions related to accountability & responsibility to the system card
Version 1.1
license and I have the …
=> Add functions to measures in the system card

docs/projects/amt/reporting-standard/latest.md
Fix indents requirements 
Version 1.1
work with modifications, whether …
=> Fix indents requirements 

docs/projects/amt/reporting-standard/0.1a12.md, docs/projects/amt/reporting-standard/latest.md, mkdocs.yml
In this PR we: 
- Adjust references schema such that it can store names and links instead of only a list. 
- Make the name attribute required. 
Version 1.1
of my knowledge, is covered under an …
=> Adjust references in systemcard schema 

aivalidation_dictionary.txt, docs/projects/amt/reporting-standard/0.1a13.md, mkdocs.yml
In this PR we update the ai-act-labels accordingly to align with the decision support tool and Algoritmekader. 
Version 1.1
license and I …
=> Align AI act label

docs/projects/amt/adrs/0007-front-end-components-implementation.md
Refined that we explicitly do not make and maintain our own NL Design System but rather make use of already existing ones.
Version 1.1 …
=> Update use of NL Design System

mkdocs.yml, requirements.txt
=> Add Plausible for analytics

mkdocs.yml
=> Exclude Plausible from privacy plugin

mkdocs.yml
=> Fix Plausible domain config

docs/projects/amt/reporting-standard/latest.md, docs/projects/amt/reporting-standard/schemas/assessmentcard_schema.json, docs/projects/amt/reporting-standard/schemas/modelcard_schema.json, docs/projects/amt/reporting-standard/schemas/systemcard_schema.json
In this PR we align the systemcard, assessment card and modelcard correctly with its schema.
Version 1.1
license and I have the right …
=> Fix systemcard schema
